
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: 1 == 2
    at Object.<anonymous> (/node/src/assert/001_fail_empty_message.js:3:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
